---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../development
  - external-secret.yaml

patches:
  - patch: |-
      $patch: delete
      apiVersion: v1
      kind: Secret
      metadata:
        name: kubearchive-logging
        namespace: kubearchive
